[package]
name = "nero-extensions"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["sync"] }
url = { version = "2.5.4", features = ["serde"] }
wasm-metadata = "0.227.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasmtime = "29.0.1"
wasmtime-wasi = "29.0.1"
wasmtime-wasi-http = "29.0.1"
