[package]
name = "nero-extensions"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
tokio = { version = "1.43.0", features = ["sync"] }
url = "2.5.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasmtime = "29.0.1"
wasmtime-wasi = "29.0.1"
wasmtime-wasi-http = "29.0.1"
