[package]
name = "tauri-plugin-video-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
m3u8-rs = "6.0.0"
minreq = { version = "2.13.4", features = ["https"] }
tauri = { version = "2", default-features = false }
tiny_http = "0.12.0"
url = "2.5.4"
urlencoding = "2.1.3"
