[package]
name = "nero-app"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tauri-plugin-shell = "2"
nero-extensions = { path = "../nero-extensions" }

[features]
custom-protocol = ["tauri/custom-protocol"]
