[package]
name = "nero-app"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.4", features = [] }

[dependencies]
tauri = { version = "1.7.2", features = ["shell-open"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[features]
custom-protocol = ["tauri/custom-protocol"]
