[package]
name = "typewind"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full", "visit"] }
typewind-macros = { path = "../typewind-macros" }
